mysite/book/urls.py
from django.conf.urls import patterns, url

from book import views

urlpatterns = patterns('',
    # ex: /polls/
    url(r'^$', views.index_view, name='index'),
    # ex: /polls/5/
    url(r'^book/(?P<book_id>\d+)/$', views.detail_view, name='detail'),
    # ex: /polls/5/results/
#    url(r'^(?P<book_id>\d+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
#    url(r'^(?P<book_id>\d+)/vote/$', views.vote, name='vote'),

    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^search/$', views.search_view, name='search'),
    url(r'^pick/$', views.pick_view, name='pick'),    
    url(r'^adjust/$', views.adjust_view, name='adjust'),    
    url(r'^cart/$', views.cart_view, name='cart'),    
    url(r'^checkout/$', views.checkout_view, name='checkout'),     
    url(r'^confirm/$', views.confirm_view, name='confirm'),     
    url(r'^bills/$', views.bills_view, name='bills'),
    url(r'^profile/$', views.profile_view, name='profile'),    
    url(r'^updateProfile/$', views.updateProfile_view, name='updateProfile'),    
)



#with below, 
# Now delelte index(), detail() and results() views from polls/views.py as they can be replacesd by generic views
# for ListView, the automatically generated context variable is poll_list for model(Poll)
# for DetailView, the automatically generated context variable is poll for model(Poll)


'''
urlpatterns = patterns('',
    url(r'^$',
        ListView.as_view(
            queryset=Poll.objects.order_by('-pub_date')[:5],
            context_object_name='latest_poll_list',
            template_name='polls/index.html'),
        name='index'),
    url(r'^(?P<pk>\d+)/$',
        DetailView.as_view(
            model=Poll,
            template_name='polls/detail.html'),
        name='detail'),
    url(r'^(?P<pk>\d+)/results/$',
        DetailView.as_view(
            model=Poll,
            template_name='polls/results.html'),
        name='results'),
    url(r'^(?P<poll_id>\d+)/vote/$', 'polls.views.vote', name='vote'),
)
'''

mysite/mysite/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^mysite/', include('mysite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^book/', include('book.urls', namespace='book')),    
)

mysite/book/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import datetime

# Create your models here.
        
class Book(models.Model):   
    title = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    #TODO
    quatity = models.IntegerField(default=10)
    in_stock = models.BooleanField()
    isbn = models.IntegerField()
    rating = models.IntegerField(default=3)
    description = models.CharField(max_length=200)
    numberOfPages = models.IntegerField()
    price = models.IntegerField()  
    authors = models.ManyToManyField('Author')

    def __unicode__(self):
        return self.title    

    def has_published(self):
        return self.pub_date <= timezone.now()

        
class Comment(models.Model): 
    book = models.ForeignKey('Book')  
    text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    author = models.ForeignKey(User)
    
    def __unicode__(self):
        return '<%s> %s' % (self.book.title, self.text)

class Author(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()

    def __unicode__(self):
        return self.name
        
        
class Bill(models.Model):   
    user = models.ForeignKey(User)
    checkout_date = models.DateTimeField('date checkouted')
    remark = models.CharField(max_length=200)
    totalPrice = models.IntegerField(default=10)
    billingAddr = models.CharField(max_length=200)
    shippingAddr = models.CharField(max_length=200)
    creditCard = models.IntegerField(default=10)
    books = models.ManyToManyField('Book')        

class UserProfile(models.Model):   
    user = models.ForeignKey(User)
    billingAddr = models.CharField(max_length=200)
    shippingAddr = models.CharField(max_length=200)
    creditCard = models.IntegerField(default=10)

mysite/book/views.py
# Create your views here.

from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db.models import F, Q
from book.models import Book, Comment, Author, Bill, UserProfile
import datetime

'''
def index(request):
    latest_poll_list = Poll.objects.all().order_by('-pub_date')[:5]
    context = {'latest_poll_list': latest_poll_list}
    return render(request, 'polls/index.html', context)
    #return HttpResponse("Hello, world. You're at the poll index.")


def detail(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    return render(request, 'polls/detail.html', {'poll': poll})  
    #return HttpResponse("You're looking at poll %s." % poll_id)

def results(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    return render(request, 'polls/results.html', {'poll': poll})
    
    
def vote(request, poll_id):
    p = get_object_or_404(Poll, pk=poll_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the poll voting form.
        return render(request, 'polls/detail.html', {
            'poll': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))
'''
def index_view(request, error_message=None):
    books = Book.objects.all() 
    return render(request, 'book/index.html', {'books': books, 'error_message': error_message})

    
def detail_view(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    return render(request, 'book/detail.html', {'book': book})  


def login_view(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            login(request, user)
            # Redirect to a success page.
            return HttpResponseRedirect(reverse('book:index'))
        else:
            # Return a 'disabled account' error message
            pass
    else:
        # Return an 'invalid login' error message.        
        return render(request, 'book/index.html', {'error_message': "Wrong username or password!"})  

@login_required(login_url='/book/')
def logout_view(request):
    logout(request)   
    return redirect(reverse('book:index'))

def search_view(request):
    if request.GET.has_key('q'):
        kw = request.GET['q']
    else:
        kw = ''
    b1 = Book.objects.filter(title__contains=kw)
    b2 = Book.objects.filter(authors__name__icontains=kw)
    b3 = Book.objects.filter(isbn__contains=kw)    
    books = set(b1) | set(b2) | set(b3)
    ### this may cause duplicate records for which has many authors
    ##books = Book.objects.filter(Q(title__contains=request.GET['q']) | Q(authors__name__icontains=request.GET['q']))
    return render(request, 'book/search.html', {'books': books})

def pick_view(request):
    book_id = request.POST['book_id']
    book = get_object_or_404(Book, pk=book_id)
    if not book.in_stock:
        return render(request, 'book/detail.html', {'error_message': "The book will be shipped when it becomes available."})  

    if not request.session.has_key('cart'):
        request.session['cart'] = {}
    if request.session['cart'].has_key(book_id):
        qty = int(request.session['cart'][book_id]) + 1
    else:  
        qty = 1  
    request.session['cart'][book_id] = qty
    request.session.modified = True
    return HttpResponseRedirect(reverse('book:index', args=()))

def adjust_view(request):
    book_id = request.POST['book_id']
    qty = int(request.POST['qty'])
    if request.session['cart'].has_key(book_id):
        request.session['cart'][book_id] = qty
    if qty <= 0:
        del request.session['cart'][book_id]       
    request.session.modified = True    
    return redirect(reverse('book:cart', args=()))


def cart_view(request):
    boughtItems = []
    totalPrice = 0
    if not request.session.has_key('cart'):
        request.session['cart'] = {}

    for (book_id, qty) in request.session['cart'].iteritems():
        boughtItems.append({'book': Book.objects.get(pk=book_id), 'qty': qty})   
        totalPrice += Book.objects.get(pk=book_id).price * qty
    request.session['totalPrice'] = totalPrice
    request.session.modified = True 
    return render(request, 'book/cart.html', {'boughtItems': boughtItems})

@login_required(login_url='/book/')
def checkout_view(request):
    totalPrice = request.session['totalPrice']
    userProfile = UserProfile.objects.get(user=request.user)
    return render(request, 'book/confirm.html', {'totalPrice': totalPrice, 'userProfile': userProfile})

@login_required(login_url='/book/')
def confirm_view(request):
    bill = Bill(user=request.user, checkout_date=datetime.datetime.now(), totalPrice=request.session['totalPrice'])
    bill.save()
    for (book_id, qty) in request.session['cart'].iteritems():
        book = Book.objects.get(pk=book_id)
        bill.books.add(book)
    bill.save()

    userProfile = UserProfile.objects.get(user=request.user)
    userProfile.billingAddr = request.POST['billingAddr']
    userProfile.shippingAddr = request.POST['shippingAddr']
    userProfile.creditCard = request.POST['creditCard']
    userProfile.save()

    request.session['cart'] = {}
    return render(request, 'book/summary.html', {'bill': bill})



@login_required(login_url='/book/')
def bills_view(request):
    bills = Bill.objects.filter(user=request.user)
    for b in bills:
        b.booksHistory = b.books.all()
    return render(request, 'book/bills.html', {'bills': bills})

@login_required(login_url='/book/')
def profile_view(request):
    userProfile = UserProfile.objects.get(user=request.user)
    return render(request, 'book/profile.html', {'userProfile': userProfile})

@login_required(login_url='/book/')
def updateProfile_view(request):
    userProfile = UserProfile.objects.get(user=request.user)
    userProfile.billingAddr = request.POST['billingAddr']
    userProfile.shippingAddr = request.POST['shippingAddr']
    userProfile.creditCard = request.POST['creditCard']
    userProfile.save()
    return redirect(reverse('book:index', args=()))

mysite/book/templates/book/base.html
<!DOCTYPE html>

<head>
{% load static %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" type="text/css" href="{% static "book/css/bootstrap.min.css" %}"/>
<link rel="stylesheet" type="text/css" href="{% static "book/css/bootstrap-responsive.min.css" %}"/>
<link rel="stylesheet" type="text/css" href="{% static "book/css/style.css" %}"/>
<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
    <script src="{% static "book/js/html5shiv.js" %}></script>
  <![endif]-->

<!-- Fav and touch icons -->
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static "book/img/apple-touch-icon-144-precomposed.png" %}">
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static "book/img/apple-touch-icon-114-precomposed.png" %}">
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static "book/img/apple-touch-icon-72-precomposed.png" %}">
<link rel="apple-touch-icon-precomposed" href="{% static "book/img/apple-touch-icon-57-precomposed.png" %}">
<link rel="shortcut icon" href="{% static "book/img/favicon.png" %}">


<script type="text/javascript" src="{% static "book/js/jquery.min.js" %}"></script>
<script type="text/javascript" src="{% static "book/js/bootstrap.min.js" %}"></script>
<script type="text/javascript" src="{% static "book/js/scripts.js" %}"></script>
</head>

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div class="navbar navbar-inverse">
                <div class="navbar-inner">
                    <div class="container-fluid">
                         <a data-target=".navbar-responsive-collapse" data-toggle="collapse" class="btn btn-navbar"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></a> <a href="#" class="brand">Book Store</a>
                        <div class="nav-collapse collapse navbar-responsive-collapse">
                            <ul class="nav">
                                <li class="active">
                                    <a href="{% url 'book:index' %}">Home</a>
                                </li>
                                <li>
                                    <a id="cart" href="{% url 'book:cart' %}">Cart</a>
                                </li>
                            </ul>
                            <ul class="nav pull-right">
                                {% if user.is_authenticated %}
                                <li>
                                    <a id="bills" href="{% url 'book:bills' %}">Bills</a>
                                </li>
                                <li>
                                    <a id="btnProfile" href="{% url 'book:profile' %}">Profile</a>
                                </li>                        
                                <li>
                                    <a id="btnLogout" href="{% url 'book:logout' %}">Logout</a>
                                </li>
                                {% endif %}
                                <li class="divider-vertical">
                                </li>
                                <li class="dropdown">
                                     <a data-toggle="dropdown" class="dropdown-toggle" href="#">Dropdown<strong class="caret"></strong></a>
                                    <ul class="dropdown-menu">
                                        <li>
                                            <a href="#">Action</a>
                                        </li>
                                        <li>
                                            <a href="#">Another action</a>
                                        </li>
                                        <li>
                                            <a href="#">Something else here</a>
                                        </li>
                                        <li class="divider">
                                        </li>
                                        <li class="nav-header">
                                            Nav header
                                        </li>
                                        <li>
                                            <a href="#">Separated link</a>
                                        </li>
                                        <li>
                                            <a href="#">One more separated link</a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        
                    </div>
                </div>                
            </div>
		</div>
	{% block content %}
	<h1>this is base template</h1>
	{% endblock %}
</div>

mysite/book/templates/book/bills.html
{% extends 'book/base.html' %}

{% block content %}


<h2>Bills History</h2>

<a href="{% url 'book:index' %}">Continoue shopping</a>

{% if bills %}
    <ul>
    {% for bill in bills %}
        <li id="billId_{{ bill.id }}">
            <p>Bill Id: {{ bill.id }}</p>
            <p>Total Price: ${{ bill.totalPrice }}</p>
            <p>Checkout Date: ${{ bill.checkout_date }}</p>
            <ol>
            {% for book in bill.booksHistory %}            
                <li><a href="{% url 'book:detail' book.id %}">{{ book.title }}</a></li>
            {% endfor %}
            </ol>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No bill in history.</p>
{% endif %}

{% endblock %}

mysite/book/templates/book/cart.html
{% extends 'book/base.html' %}

{% block content %}



<h2>Shopping Cart</h2>
<a href="{% url 'book:index' %}">Continoue shopping</a>
{% if boughtItems %}
    <ul>
    {% for item in boughtItems %}
        <li>
            <a href="{% url 'book:detail' item.book.id %}">{{ item.book.title }}</a>
            <form action="{% url 'book:adjust' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" id="book_id" name="book_id" value="{{ item.book.id }}" />
                <label for="qty">Qty:</lable><input id="qty" name="qty" value="{{ item.qty }}" />
                <input type="submit" id="adjust" value="Adjust" />
            </form>
        </li>
    {% endfor %}
    </ul>
    <form action="{% url 'book:checkout' %}" method="POST">
        {% csrf_token %}
        <input type="submit" id="checkout" value="Checkout" />        
    </form>
    
{% else %}
    <p>No book in cart.</p>
{% endif %}

{% endblock %}

mysite/book/templates/book/confirm.html
{% extends 'book/base.html' %}

{% block content %}


<h2>Shopping Cart</h2>
<a href="{% url 'book:cart' %}">Back to Cart</a>
<a href="{% url 'book:index' %}">Continoue shopping</a>

<p>Total Price: ${{ totalPrice }}</p>
<form action="{% url 'book:confirm' %}" method="POST">
    {% csrf_token %}
    <label for="billingAddr">Billing Addr</lable><input id="billingAddr" name="billingAddr" value="{{ userProfile.billingAddr }}" /><br/>
    <label for="shippingAddr">Shipping Addr</lable><input id="shippingAddr" name="shippingAddr" value="{{ userProfile.shippingAddr }}" /><br/>
    <label for="creditCard">Credit Card</lable><input id="creditCard" name="creditCard" value="{{ userProfile.creditCard }}" /><br/>
    <input type="submit" id="btnConfirm" value="Confirm" />        
</form>
    
{% endblock %}

mysite/book/templates/book/detail.html
{% extends 'book/base.html' %}

{% block content %}

<h1>{{ book.title }}</h1>
<a href="{% url 'book:index' %}">Continoue shopping</a>

<form action="{% url 'book:pick' %}" method="POST">
    {% csrf_token %}
    <input type="hidden" name="book_id" value="{{book.id}}" />
    <input class="btn" type="submit" id="btnAddToCart" value="Add to Cart" />
</form>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<p>Publish Date: {{ book.pub_date }}</p>
<p>ISBN: {{ book.isbn }}</p>
<p>{% if book.in_stock %} In-Stock {% else %} Out-of-Stock {% endif%} </p>
<p>Description: {{ book.description }}</p>
<p>{{ book.numberOfPages }} page{{ book.numberOfPages|pluralize }}</p>
<p>Price: ${{ book.price }}</p>


<article>Authors:<article>
<ul>
{% for author in book.authors.all %}
    <li>{{ author.name }} ({{ author.email }})</li>
{% endfor %}
</ul>

<article>Comments:<article>
<ul>
{% for comment in book.comment_set.all %}
    <li>{{ comment.text }} -- by {{ comment.author.username }} at {{ comment.pub_date }}</li>
{% endfor %}
</ul>

{% load static %}
<img src="{% static "book/book.jpg" %}" alt="My image" class="img-thumbnail"/>

{% endblock %}

mysite/book/templates/book/index.html
{% extends 'book/base.html' %}


{% block content %}
            <div class="row-fluid">
                <div class="span8">
                    <form class="form-search" action="{% url 'book:search' %}" method="get">
                        <input type="text" class="input-medium search-query" id="q" name="q" placeholder="9876 books" />
                        <button class="btn" type="submit" id="search">Search</button>
                    </form>
                    {% if books %}
                        <ul>
                        {% for book in books %}
                            <li><a id="isbn_{{ book.isbn }}" href="{% url 'book:detail' book.id %}">{{ book.title }}</a></li>
                        {% endfor %}
                        </ul>
                    {% else %}
                        <p>No book are in stock.</p>
                    {% endif %}
                </div>
                <div class="span4">        
                    {% if user.is_authenticated %}
                    <div class="alert alert-info">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <h4>
                            Welcome!
                        </h4> <strong>{{ user.username }}</strong>, Thanks for logging in.
                        {% if notify_message %}<strong>{{ notify_message }}</strong>{% endif %}
                    </div>
                    {% else %}

                    {% if error_message %}
                    <div class="alert">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <h4>
                            {{ error_message }}
                        </h4>
                    </div>
                    {% endif %}
                    <form action="{% url 'book:login' %}" method="post">
                        {% csrf_token %}
                        <fieldset>
                            <legend>Login</legend>
                            <label for="username">Username</label>
                            <input type="text" id="username" name="username" placeholder="username" value="uperform" />
                            <label for="password">Password</label>
                            <input type="password" id="password" name="password" placeholder="password" value="uperform" />
                            <button type="submit" id="btnLogin" value="Login" class="btn">Submit</button>
                        </fieldset>
                    </form>

                    {% endif %}

                </div>
            </div>
        </div>
{% endblock %}

mysite/book/templates/book/profile.html
{% extends 'book/base.html' %}

{% block content %}



<h2>User Profile</h2>
<a href="{% url 'book:index' %}">Continoue shopping</a>

<form action="{% url 'book:updateProfile' %}" method="POST">
    {% csrf_token %}
    <div class="form-group">
	    <label for="billingAddr">Billing Addr</label>
	    <input class="form-control" id="billingAddr" name="billingAddr" value="{{ userProfile.billingAddr }}" /><br/>
	    <label for="shippingAddr">Shipping Addr</label>
	    <input class="form-control" id="shippingAddr" name="shippingAddr" value="{{ userProfile.shippingAddr }}" /><br/>
	    <label for="creditCard">Credit Card</label>
	    <input class="form-control" id="creditCard" name="creditCard" value="{{ userProfile.creditCard }}" /><br/>
    </div>
    <button type="submit" id="btnUpdate" class="btn btn-primary">Update</button>
</form>

<a id="btnCancel" href="{% url 'book:index' %}">cancel</a>

{% endblock %}

mysite/book/templates/book/search.html
{% extends 'book/base.html' %}

{% block content %}


<div>
    <form action="{% url 'book:search' %}" method="get">
        <input id="q" name="q" placeholder="9876 books" />
        <button class="btn" type="submit" id="search">Search</button>
    </form>
</div>
{% if books %}
    <p>Found {{ books|length }} book{{ books|pluralize }}:</p>
    <ul>
    {% for book in books %}
        <li><a id="isbn_{{ book.isbn }}" href="{% url 'book:detail' book.id %}">{{ book.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No book are in stock.</p>
{% endif %}

{% endblock %}

mysite/book/templates/book/summary.html
{% extends 'book/base.html' %}

{% block content %}



<h2>Checkout Summary</h2>

<a href="{% url 'book:index' %}">Continoue shopping</a>
<a href="{% url 'book:bills' %}">Bills history</a>

    <p>Success.</p>
    <p>Bill Id: <span id="billId">{{ bill.id }}</span></p>
    <p>Total Price: ${{ bill.totalPrice }}</p>
    <p>Checkout Date: ${{ bill.checkout_date }}</p>
    <ol>
    {% for book in bill.booksHistory %}            
        <li><a href="{% url 'book:detail' book.id %}">{{ book.title }}</a></li>
    {% endfor %}
    </ol>

{% endblock %}